public enum TransactionType
{
    COLLECTION,
    PAYMENT,
    ADJUSTMENT,
    XCL_LOADER,
    TRIGGER,
    TO_CATEGORIZE,
    INCOMING_PAYMENT,
    DIRECT_DEBIT,
    MANUAL_OUTGOING,
    OUTGOING_PAYMENT,
    EXTERNAL_DEBIT_PAYMENT
}
